server {
    listen 80;
    server_name www.shenas.net;
    return 301 https://shenas.net$request_uri;
}

server {
    listen 80 default_server;
    server_name shenas.net;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
