apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shenas-ingress
  namespace: shenas
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "shenas-cert"
    kubernetes.io/ingress.global-static-ip-name: "shenas-ip"
spec:
  rules:
    - host: repo.shenas.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: repo-server
                port:
                  number: 80
    - host: fl.shenas.dev
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fl-server-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fl-server-grpc
                port:
                  number: 8080
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: shenas-cert
  namespace: shenas
spec:
  domains:
    - repo.shenas.dev
    - fl.shenas.dev
