apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shenas-ingress
  namespace: shenas
  annotations:
    networking.gke.io/managed-certificates: "shenas-cert"
    kubernetes.io/ingress.global-static-ip-name: "shenas-ip"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: shenas.net
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: web-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shenas-net
                port:
                  number: 80
    - host: www.shenas.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shenas-net
                port:
                  number: 80
    - host: repo.shenas.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-api
                port:
                  number: 80
    - host: fl.shenas.net
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: fl-server-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fl-server-grpc
                port:
                  number: 8080
    - host: shenas.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shenas-org
                port:
                  number: 80
    - host: www.shenas.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shenas-org
                port:
                  number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: shenas-cert
  namespace: shenas
spec:
  domains:
    - shenas.net
    - www.shenas.net
    - repo.shenas.net
    - fl.shenas.net
    - shenas.org
    - www.shenas.org
