FROM node:22-slim AS build
WORKDIR /app
COPY server/shenas.net/package.json server/shenas.net/package-lock.json ./
RUN npm ci
COPY server/shenas.net/ .
RUN npm run build

FROM nginx:1-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY server/shenas.net/nginx.conf /etc/nginx/conf.d/shenas.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
