server {
    listen 80;
    server_name shenas.org www.shenas.org;

    if ($host = www.shenas.org) {
        return 301 https://shenas.org$request_uri;
    }

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
