"""Job correlation -- contextvar-bound job_id for long-running operations.

A "job" is one user-triggered backend operation that produces a stream of progress
events and Python log records: a sync, a plugin install, a plugin remove. Each gets
a stable 16-char `job_id` generated by the backend, broadcast to the frontend in the
first SSE event so the job panel can adopt it, and bound to a ContextVar for the
lifetime of the request so a logging filter can tag every emitted LogRecord. The
OTel log exporter then persists the id into `telemetry.logs.attributes` so historical
queries like::

    SELECT json_extract_string(attributes, '$.job_id') AS jid, message
    FROM telemetry.logs
    WHERE jid = '<id>'
    ORDER BY timestamp;

work end-to-end.
"""

from __future__ import annotations

import logging
from contextlib import contextmanager
from contextvars import ContextVar
from typing import TYPE_CHECKING
from uuid import uuid4

if TYPE_CHECKING:
    from collections.abc import Iterator


current_job_id: ContextVar[str | None] = ContextVar("current_job_id", default=None)


def new_job_id() -> str:
    """Generate a fresh 16-char job id."""
    return uuid4().hex[:16]


def get_job_id() -> str | None:
    """Return the job id bound to the current context, or None if outside one."""
    return current_job_id.get()


@contextmanager
def bind_job_id(job_id: str | None) -> Iterator[str | None]:
    """Bind a job id to the current context for the duration of the with-block.

    ContextVars do NOT propagate across `threading.Thread` boundaries automatically.
    Workers that spawn threads must capture `get_job_id()` outside the thread and
    re-call `bind_job_id(captured)` inside the worker.

    Restores the previous value directly instead of using ``ContextVar.reset(token)``
    so the binding survives crossing context boundaries (e.g. Starlette iterating a
    streaming-response generator in a different task than where it was constructed).
    """
    previous = current_job_id.get()
    current_job_id.set(job_id)
    try:
        yield job_id
    finally:
        current_job_id.set(previous)


class JobIdLogFilter(logging.Filter):
    """Inject the current job_id into every LogRecord.

    The OTel `LoggingHandler` bridges stdlib LogRecord extras into the OTel record's
    attributes dict, so the value set here flows through to `DuckDBLogExporter` and
    ends up persisted into the `telemetry.logs.attributes` JSON column.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        record.job_id = current_job_id.get()
        return True
